# Generated by Django 5.0.6 on 2024-05-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='active_status',
            new_name='completed_status',
        ),
    ]
