# Generated by Django 5.0.6 on 2024-05-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cie', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIECategorywiseMarksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField(default=0)),
                ('cie_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cie.cie')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='students.student', to_field='student_id')),
            ],
        ),
        migrations.CreateModel(
            name='CIEMarksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial', models.FloatField(default=0)),
                ('assignment', models.FloatField(default=0)),
                ('curricular', models.FloatField(default=0)),
                ('quiz', models.FloatField(default=0)),
                ('course_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='students.student', to_field='student_id')),
            ],
        ),
        migrations.CreateModel(
            name='SEEMarksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo1', models.FloatField(default=0)),
                ('clo2', models.FloatField(default=0)),
                ('clo3', models.FloatField(default=0)),
                ('clo4', models.FloatField(default=0)),
                ('clo5', models.FloatField(default=0)),
                ('course_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('exam_roll', models.ForeignKey(db_column='exam_roll', on_delete=django.db.models.deletion.CASCADE, to='students.student', to_field='exam_roll')),
            ],
        ),
    ]
